// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ2FmpQ9EIu_IBV9mvZOc5ZNd76CsvfX4',
    appId: '1:694150969145:web:88fce815c4614be1705ae8',
    messagingSenderId: '694150969145',
    projectId: 'act17-a7487',
    authDomain: 'act17-a7487.firebaseapp.com',
    storageBucket: 'act17-a7487.firebasestorage.app',
    measurementId: 'G-2E584FZF2G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEXxKPkR-nCAWCcbAPwyEwrAgJTvEmEPA',
    appId: '1:694150969145:android:0327f3db50c59dc6705ae8',
    messagingSenderId: '694150969145',
    projectId: 'act17-a7487',
    storageBucket: 'act17-a7487.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa1KQZEDKEgBZpevaiyt56CJ2p0qrcauk',
    appId: '1:694150969145:ios:6b0e6f3d80a87246705ae8',
    messagingSenderId: '694150969145',
    projectId: 'act17-a7487',
    storageBucket: 'act17-a7487.firebasestorage.app',
    iosBundleId: 'com.example.act17',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCa1KQZEDKEgBZpevaiyt56CJ2p0qrcauk',
    appId: '1:694150969145:ios:6b0e6f3d80a87246705ae8',
    messagingSenderId: '694150969145',
    projectId: 'act17-a7487',
    storageBucket: 'act17-a7487.firebasestorage.app',
    iosBundleId: 'com.example.act17',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJ2FmpQ9EIu_IBV9mvZOc5ZNd76CsvfX4',
    appId: '1:694150969145:web:9dbc7bff9b4fb3c9705ae8',
    messagingSenderId: '694150969145',
    projectId: 'act17-a7487',
    authDomain: 'act17-a7487.firebaseapp.com',
    storageBucket: 'act17-a7487.firebasestorage.app',
    measurementId: 'G-S85EVSHBKF',
  );
}
